import PDFDocument from 'pdfkit';
import { RunState, RunStep } from './types.js';

export async function generateStepPDF(runState: RunState, step: RunStep): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        // Title Page
        doc.fontSize(24).fillColor('#333333').text('AI Agent Factory - Step Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(16).text(`Mission: ${runState.mission}`, { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Run ID: ${runState.runId}`, { align: 'center' });
        doc.text(`Tenant: ${runState.tenantId}`, { align: 'center' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
        doc.moveDown(2);

        // Header for Step
        doc.rect(50, doc.y, 500, 40).fill('#f0f0f0').stroke();
        doc.fillColor('#000000').fontSize(14).text(`Step ${step.step}: ${step.agentId.toUpperCase()}`, 60, doc.y - 30);
        doc.moveDown(2);

        // Summary Section
        doc.fontSize(16).text('Executive Summary', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).text(step.deliverables?.summaryMarkdown || 'No summary provided.');
        doc.moveDown(1.5);

        // Action Items (TODOs)
        doc.fontSize(16).text('Action Items (Next Steps)', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).text(step.deliverables?.todoMarkdown || 'No action items.');
        doc.moveDown(1.5);

        // Key Data / Output
        doc.addPage();
        doc.fontSize(16).text('Key Data Artifacts', { underline: true });
        doc.moveDown(0.5);

        if (step.deliverables?.outputJson) {
            const jsonStr = JSON.stringify(step.deliverables.outputJson, null, 2);
            doc.fontSize(10).font('Courier').text(jsonStr);
        } else {
            doc.fontSize(12).text('No structured data produced.');
        }

        // Footer
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
            doc.switchToPage(i);
            doc.fontSize(8).text(
                `Generated by AI Factory v3.1 | Page ${i + 1} of ${range.count}`,
                50,
                doc.page.height - 50,
                { align: 'center' }
            );
        }

        doc.end();
    });
}
